title: OpenTurbine
description: Open-source ESP32 gas turbine ECU for DIY turbojet, turboprop and free-turbine engine projects.
url: https://elia179.github.io
baseurl: /OpenTurbine-ESP32-Gas-Turbine-ECU
repository: elia179/OpenTurbine-ESP32-Gas-Turbine-ECU
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
image: /assets/images/social-preview.png
twitter:
  card: summary_large_image
google_site_verification:
exclude:
  - Gemfile
  - Gemfile.lock
