#!/usr/bin/env python3
"""Assemble maintainable page sources into the single-request ECU pages.

Large pages keep markup and JavaScript in focused source files under
data_src/pages/. The generated data_src/*.html files intentionally retain one
inline script: this avoids extra HTTP requests on the ECU access point and
keeps the existing browser/audit behavior deterministic.
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "data_src"
PAGES = SRC / "pages"

PAGE_MANIFEST = {
    "hardware.html": (
        "hardware.shell.html",
        (
            "hardware-pins.js",
            "hardware-state.js",
            "hardware-registry-catalog.js",
            "hardware-registry-view.js",
            "hardware-registry-actions.js",
            "hardware-dependencies.js",
            "hardware-validation.js",
            "hardware-save.js",
        ),
    ),
    "sequence.html": (
        "sequence.shell.html",
        (
            "sequence-definitions.js",
            "sequence-state.js",
            "sequence-editor.js",
            "sequence-rules-save.js",
            "sequence-runtime.js",
        ),
    ),
    "config.html": (
        "config.shell.html",
        (
            "config-schema.js",
            "config-render.js",
            "config-validation-save.js",
            "config-runtime.js",
        ),
    ),
}

PLACEHOLDER = "<!-- OT_PAGE_SCRIPTS -->"
GENERATED_NOTE = (
    "<!-- GENERATED by tools/build_web_sources.py; edit data_src/pages/* instead. -->"
)


def assemble(output_name: str, shell_name: str, script_names: tuple[str, ...]) -> None:
    shell = (PAGES / shell_name).read_text(encoding="utf-8")
    if shell.count(PLACEHOLDER) != 1:
        raise RuntimeError(f"{shell_name} must contain exactly one {PLACEHOLDER}")
    scripts = []
    for name in script_names:
        body = (PAGES / name).read_text(encoding="utf-8").rstrip()
        scripts.append(f"// Source: data_src/pages/{name}\n{body}")
    inline = "<script>\n" + "\n\n".join(scripts) + "\n</script>"
    generated = shell.replace(PLACEHOLDER, inline)
    if not generated.startswith(GENERATED_NOTE):
        generated = GENERATED_NOTE + "\n" + generated
    output = SRC / output_name
    old = output.read_text(encoding="utf-8") if output.exists() else None
    if old != generated:
        output.write_text(generated, encoding="utf-8", newline="\n")
        print(f"  assembled {output_name}")


def main() -> None:
    for output_name, (shell_name, scripts) in PAGE_MANIFEST.items():
        assemble(output_name, shell_name, scripts)


if __name__ == "__main__":
    main()
